version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASS}
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASS}
      MYSQL_TCP_PORT: ${SQL_PORT}
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    volumes:
      - ${MYSQL_DIRECTORY}:/var/lib/mysql
    restart: always

  redis:
    logging:
      driver: none
    image: redis
    restart: always
    command: "redis-server --port ${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DIRECTORY}:/data

  realistikgdps:
    image: realistikgdps:latest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
      - redis
      - meilisearch
      - datadog
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - APP_URL_PREFIX=${APP_URL_PREFIX}

      - SQL_HOST=${SQL_HOST}
      - SQL_USER=${SQL_USER}
      - SQL_PASS=${SQL_PASS}
      - SQL_DB=${SQL_DB}
      - SQL_PORT=${SQL_PORT}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

      - MEILI_HOST=${MEILI_HOST}
      - MEILI_PORT=${MEILI_PORT}
      - MEILI_KEY=${MEILI_KEY}

      - S3_ENABLED=${S3_ENABLED}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}

      - SERVER_NAME=${SERVER_NAME}
      - SERVER_COMMAND_PREFIX=${SERVER_COMMAND_PREFIX}
      - SERVER_GD_URL=${SERVER_GD_URL}
      - SERVER_STATELESS=${SERVER_STATELESS}

      - DD_ENABLED=${DD_ENABLED}
      - DD_HOST=${DD_HOST}
      - DD_PORT=${DD_PORT}
      - DD_STATS_HOST=${DD_STATS_HOST}
      - DD_STATS_PORT=${DD_STATS_PORT}
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_LOGS_INJECTION=true
      - DD_SERVICE=realistikgdps
      - DD_LOGS_ENABLED=true

      # Internal docker specific variables
      - INTERNAL_RGDPS_DIRECTORY=/data # NOTE: Ensure this matches the volume mount below.
      - APP_COMPONENT=${APP_COMPONENT:-api}
    volumes:
      - .:/app
      - ${RGDPS_DIRECTORY}:/data # <- INTERNAL_RGDPS_DIRECTORY

  meilisearch:
    image: getmeili/meilisearch:v1.3.1
    restart: always
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - ${MEILI_DIRECTORY}:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_KEY}
      - MEILI_HTTP_ADDR=0.0.0.0:${MEILI_PORT}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=${SQL_HOST}
      - PMA_PORT=${SQL_PORT}
      - UPLOAD_LIMIT=500M
    depends_on:
      - mysql

  datadog:
    image: gcr.io/datadoghq/agent:7
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_TRACE_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - .:/data
      - ./datadog/conf.d:/etc/datadog-agent/conf.d
